# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# scan with Anchore's Syft tool, and uploads the results to the GitHub Dependency
# submission API.

# For more information on the Anchore sbom-action usage
# and parameters, see https://github.com/anchore/sbom-action. For more
# information about the Anchore SBOM tool, Syft, see
# https://github.com/anchore/syft
name: Anchore Syft SBOM scan

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: write # required to upload to the Dependency submission API
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Scan Conanfile and upload dependency results
      uses: anchore/sbom-action@fc46e51fd3cb168ffb36c6d1915723c47db58abb
      with:
        file: ./conanfile.txt
        artifact-name: conan.spdx.json
        dependency-snapshot: true
    - name: Scan LuaRocks manifest and upload dependency results
      uses: anchore/sbom-action@fc46e51fd3cb168ffb36c6d1915723c47db58abb
      with:
        file: ./fmadio20.rockspec
        artifact-name: luarocks.spdx.json
        dependency-snapshot: true
