name: OSV-Scanner PR Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  get-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: cURL
        id: curl
        env:
          BEARER: ${{ secrets.BEARER }}
        run: |
          curl -L -o spdx.sbom.json -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer $BEARER" https://api.github.com/repos/jerome-fmad/sbom-testing/dependency-graph/sbom
  scan-pr:
    needs: get-sbom
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.8.5"
    with:
      scan-args: |-
        --sbom=spdx.sbom.json
      upload-sarif: false
