bname: OSV-Scanner PR Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  get-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: cURL
        id: curl
        env:
          BEARER: ${{ secrets.BEARER }}
        run: |
          curl -L -o ./spdx.sbom.json -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer $BEARER" https://api.github.com/repos/jerome-fmad/sbom-testing/dependency-graph/sbom
      - name: SBOM Upload
        id: sbom-upload
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: ./spdx.sbom.json
  scan-pr:
    needs: get-sbom
    runs-on: ubuntu-latest
    steps:
      - name: SBOM Download
        id: sbom-download
        uses: actions/download-artifact@v4
        with:
          name: sbom
      - name: De-nest JSON
        id: sbom-denest
        run: cat spdx.sbom.json | jq '.sbom' > _spdx.sbom.json 
      - name: URI-decode JSON
        id: sbom-decode
        run: '"${*//+/ }"; echo -e "${_//%/\\x}" > spdx.sbom.json'
      - name: SBOM Scan
        uses: google/osv-scanner-action/osv-scanner-action@cbb0295db259bba04d38625792c18646ed18bc89 # v1.9.1
        with:
          scan-args: |-
            --output=results.json
            --format=json
            --sbom=spdx.sbom.json
        continue-on-error: true
      - name: Results Upload
        id: results-upload
        uses: actions/upload-artifact@v4
        with:
          name: osv-scan-results
          path: ./results.json
