name: SBOM
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
jobs:
  submit-fetch-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LuaJIT
        id: install-luajit
        run: sudo apt install luajit
      - name: Dependency Submission Preview
        id: submit-deps-preview
        env:
          GITHUB_JOB: ${{ github.job }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          BEARER: ${{ secrets.BEARER }}
        run: ./sbom.lua --dry-run --correlator "$GITHUB_WORKFLOW-$GITHUB_JOB" | jq
      - name: Submit Dependencies
        id: submit-deps
        env:
          GITHUB_JOB: ${{ github.job }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          BEARER: ${{ secrets.BEARER }}
        run: ./sbom.lua --correlator "$GITHUB_WORKFLOW-$GITHUB_JOB"
      - name: Sleep # Ensure SBOM has time to generate from dependency snapshot.
        id: sleep
        run: sleep 5
      - name: Fetch SBOM
        id: fetch-sbom
        env:
          BEARER: ${{ secrets.BEARER }}
        run: |
          curl -L -o ./spdx.sbom.json -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer $BEARER" https://api.github.com/repos/jerome-fmad/sbom-testing/dependency-graph/sbom
      - name: De-nest JSON
        id: sbom-denest
        run: cat spdx.sbom.json | jq '.sbom' > _spdx.sbom.json 
      - name: URI-decode JSON
        id: sbom-decode
        # https://stackoverflow.com/questions/6250698/how-to-decode-url-encoded-string-in-shell
        run: 'function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; } ; urldecode "$(cat _spdx.sbom.json)" > spdx.sbom.json'
      - name: SBOM Scan
        uses: google/osv-scanner-action/osv-scanner-action@cbb0295db259bba04d38625792c18646ed18bc89 # v1.9.1
        with:
          scan-args: |-
            --output=results.json
            --format=json
            --sbom=spdx.sbom.json
        continue-on-error: true
      - name: Results Upload
        id: results-upload
        uses: actions/upload-artifact@v4
        with:
          name: osv-scan-results
          path: ./results.json
